using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;

using KLib;
using KLibU;
using System;

using C462.Shared;

/// <summary>
/// Centralized place to specify the locations for the various data files generated by the game.
/// </summary>
public static class FileLocations

{    public static string StateFile
    {
        get { return Path.Combine(Application.persistentDataPath, "state.xml"); }
    }

    public static string ProjectMetadata(string project)
    {
        return Path.Combine(SharedFileLocations.HtsProjectRootFolder, project, "pmd.bin");
    }

    public static string TinnitusMatchHistoryFile { get { return Path.Combine(SharedFileLocations.HtsSubjectFolder, "meta", "tmh.json"); } }

    // Paths to project manager file
    public static string ProjectStatePath { get { return Path.Combine(SharedFileLocations.HtsSubjectFolder, "meta", "ps.json"); } }

}
