<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <FileVersion>2.1.30</FileVersion>
	  <AssemblyVersion>2.1.30</AssemblyVersion>
	  <Version>2.1.30</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="C462.Shared.UI" Version="1.8.0" />
  </ItemGroup>

</Project>